name: 'Create Kubernetes context'
description: |
  Create a kubernetes context. The context will be created using the provided API server URL and certificate authority data.

  For authentication, the action uses a [GitHub OIDC token](https://docs.github.com/en/actions/concepts/security/openid-connect#overview-of-openid-connect-oidc)
  to request a short-lived token from GitHub's OIDC provider.

  This action requires that your Kubernetes cluster is configured to trust tokens issued by GitHub's OIDC provider.

  In order to request a token, this action requires the following permissions:

  ```yaml
  permissions:
    id-token: write
    contents: read
  ```

author: EIDP

inputs:
  cluster:
    description:
      'The cluster to create the context for (e.g. development, staging,
      production).'
    required: false
    default: 'development'
  api-server:
    description: 'The API server URL for the Kubernetes cluster.'
    required: true
    default: ''
  certificate-authority-data:
    description:
      'The base64 encoded certificate authority data for the Kubernetes cluster.'
    required: true
    default: ''
  kubectl-version:
    description: 'The version of kubectl to use.'
    required: false
    default: 'latest'
  print-jwt-claims:
    description:
      'Print the JWT claims from the OIDC token for debugging purposes.'
    required: false
    default: 'false'

outputs:
  context-name:
    description: 'The name of the created Kubernetes context.'

runs:
  using: 'node24'
  main: 'dist/index.js'
