name: 'Verify Up'
description: |
  This actions verifies whether the deployment specified in by the provided inputs is up and running.
  It checks the status of the deployment in the specified Kubernetes namespace.
  
  A kubernetes context must already be configured prior to using this action.
  Checkout the [Create Kubernetes context](./create-context) action to create and configure a kubernetes context.

author: EIDP

inputs:
  environment:
    description: 'The github environment used to deploy to (e.g. `pr-\$\{\{ github.event.pr \}\}`).'
    required: true
    default: ''
  kubernetes-context:
    description: 'The name of the Kubernetes context to use for verification.'
    required: true
    default: ''
  namespace:
    description: 'The Kubernetes namespace where the deployment is located.'
    required: true
    default: ''
  flux-resource:
    description: 'The Flux resource path of the deployment to verify (e.g. helmreleases/my-release or kustomization/my-release).'
    required: true
    default: ''
  chart-version:
    description: 'Specify the chart-version input in case you want to verify if a specific version of a Helm chart is deployed.'
    required: false
    default: ''
  timeout:
    description: 'The time to wait for the deployment to be completed successfully. After the timeout is reached, the job will fail. Example timeout values: 3m, 90s, 2.5m, 2m30s'
    required: false
    default: '3m'
  pod-selector:
    description: |
      For namespaces containing multiple deployments, you can specify a pod selector to ensure that only pods belonging
      to this deployment are evaluated for successful deployment.
      The pod selector uses label selectors, such as app=my-app.
      For advanced usage, refer to the Kubernetes documentation: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering
    required: false
    default: ''
  important-workloads:
    description: |
      Space-separated list of resources for which logs should be displayed during the verify step,
      such as `deploy/my-server` or `job/my-job`.
    required: false
    default: ''
  ingress-selector:
    description: 'Label selector to identify the ingress resource for URL discovery (e.g. app=my-app). If multiple ingresses exist without a selector, a warning will be logged.'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for posting PR comments. Only posts comments if token is provided and running in PR context. Required permissions: contents:read, pull-requests:write, issues:write.'
    required: false
    default: ''

outputs:
  url:
    description: 'The discovered application URL from the ingress resource (empty if not found).'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '20'

    - name: Verify deployment is up
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_KUBERNETES-CONTEXT: ${{ inputs.kubernetes-context }}
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_FLUX-RESOURCE: ${{ inputs.flux-resource }}
        INPUT_CHART-VERSION: ${{ inputs.chart-version }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_POD-SELECTOR: ${{ inputs.pod-selector }}
        INPUT_IMPORTANT-WORKLOADS: ${{ inputs.important-workloads }}
        INPUT_INGRESS-SELECTOR: ${{ inputs.ingress-selector }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}

    - name: Kubernetes namespace report
      uses: jupyterhub/action-k8s-namespace-report@ccc0e3c37860245f3906e3857df01b0a53f9c3f8 # v1.2.0
      with:
        namespace: ${{ inputs.namespace }}
        pod-selector: ${{ inputs.pod-selector }}
        important-workloads: ${{ inputs.important-workloads }}
      if: always()
